### ISSUE TITLE
DEPNotify script

### ISSUE THREAD

**Issue by opus-nbonenberger** [aysiu/Mac-Scripts-and-Profiles#8]
Hi Alan,

I used your script at https://github.com/aysiu/Mac-Scripts-and-Profiles/blob/main/DEPNotifyMunkiSample.sh as a basis for my script to install all pending installations on first setup of a machine. Unfortunately DEPNotify instantly completes and does not display the status and progress from Munki. Instead, it seems that the `managedsoftwareupdate` process is running in the background. Can you help me here?

**Comment by aysiu** [comment]
Honestly, I just shared this as more of a "works for me, may help you, too" and not a product to be supported, and I don't think GitHub is the best place for support.

I'd recommend asking for help on [the #depnotify channel on the MacAdmins Slack.](https://app.slack.com/client/T04QVKUQG/C523HLQ83)

**Comment by opus-nbonenberger** [comment]
FYI found no other way of contacting you.
